import type { Metadata } from "next";
import { Geist, Headland_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const headlandOne = Headland_One({
  variable: "--font-headland-one",
  subsets: ["latin"],
  weight: "400"
});


export const metadata: Metadata = {
  title: "Nkyene Turtle Project",
  description: "Generated by Nkyene Turtle Project",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${headlandOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
