import type { Metadata } from "next";
import { Geist, Headland_One } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const headlandOne = Headland_One({
	variable: "--font-headland-one",
	subsets: ["latin"],
	weight: "400",
});

export const metadata: Metadata = {
	title: "Nkyene Turtle Project",
	description: "Generated by Nkyene Turtle Project",
	icons: {
		icon: "/favicon.png",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${headlandOne.variable} antialiased`}>
				<Navigation />
				{children}
				<Footer />
			</body>
		</html>
	);
}
